# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


use_frameworks!

target 'Test' do
  #comment crap
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase'
end

